# Why YAML aliases not working?? Since 2019 the feature has been requested and still not implemented in dependabot-core.
# C'mon do it already!

version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Riyadh
    assignees:
      - alashoor89
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Riyadh
    assignees:
      - alashoor89
    open-pull-requests-limit: 5
