name: invoice_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: 3.28.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  # hooks
  flutter_hooks: ^0.21.2
  # riverpod
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  # freezed & json
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # routing
  go_router: ^15.1.3
  # network
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  # I/O and storage handling
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  # localization
  intl: ^0.20.2
  # utility
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  loading_indicator: ^3.1.1
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  json_serializable: ^6.9.4
  freezed: ^3.0.0-0.0.dev
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
